services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - eduquest

  # web:
  #   build: .
  #   restart: always
  #   ports:
  #     - 81:8080
  #   depends_on:
  #     - db
  #   networks:
  #     - eduquest

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - eduquest

# networks:
#   postgresql:
# volumes:
#   postgresql-volume:
#     external: true

volumes:
  db:
    driver: local

networks:
  eduquest:
    driver: bridge
